In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Desktop/WORK/survey_results_public.csv')

In [3]:
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [4]:
df.shape

(88883, 85)

In [22]:
df1 = pd.read_csv('Desktop/WORK/survey_results_schema.csv',index_col='Column')

In [23]:
df.iloc[[0,5]]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
5,6,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,28.0,Man,No,Straight / Heterosexual,East Asian,No,Too long,Neither easy nor difficult

In [10]:
df['WelcomeChange'].value_counts()

Just as welcome now as I felt last year                    62661
Somewhat more welcome now than last year                    8853
A lot more welcome now than last year                       4808
Somewhat less welcome now than last year                    4259
Not applicable - I did not use Stack Overflow last year     2675
A lot less welcome now than last year                       2599
Name: WelcomeChange, dtype: int64

In [11]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [14]:
df['BetterLife'].value_counts()

Yes    54938
No     31331
Name: BetterLife, dtype: int64

In [16]:
df['Gender'].value_counts()

Man                                                            77919
Woman                                                           6344
Non-binary, genderqueer, or gender non-conforming                597
Man;Non-binary, genderqueer, or gender non-conforming            181
Woman;Non-binary, genderqueer, or gender non-conforming          163
Woman;Man                                                        132
Woman;Man;Non-binary, genderqueer, or gender non-conforming       70
Name: Gender, dtype: int64

In [19]:
df['Ethnicity'].value_counts()

White or of European descent                                                                                                                                  50929
South Asian                                                                                                                                                    8373
East Asian                                                                                                                                                     3510
Hispanic or Latino/Latina                                                                                                                                      3474
Middle Eastern                                                                                                                                                 2580
                                                                                                                                                              ...
East Asian;Middle Eastern;White or of European descent;Biracial                                                                                                   1
Hispanic or Latino/Latina;Native American, Pacific Islander, or Indigenous Australian;Biracial                                                                    1
Black or of African descent;East Asian;Middle Eastern;Native American, Pacific Islander, or Indigenous Australian;White or of European descent;Multiracial        1
Black or of African descent;South Asian;White or of European descent                                                                                              1
Black or of African descent;Middle Eastern;Native American, Pacific Islander, or Indigenous Australian                                                            1
Name: Ethnicity, Length: 196, dtype: int64

In [28]:
df1.loc['Ethnicity','QuestionText']

'Which of the following do you identify as? Please check all that apply. If you prefer not to answer, you may leave this question blank.'

In [29]:
df1.sort_index()

                                                    QuestionText
Column
Age            What is your age (in years)? If you prefer not...
Age1stCode     At what age did you write your first line of c...
BetterLife     Do you think people born today will have a bet...
BlockchainIs   Blockchain / cryptocurrency technology is prim...
BlockchainOrg  How is your organization thinking about or imp...
...                                                          ...
WorkPlan                 How structured or planned is your work?
WorkRemote                       How often do you work remotely?
WorkWeekHrs     On average, how many hours per week do you work?
YearsCode      Including any education, how many years have y...
YearsCodePro   How many years have you coded professionally (...

[85 rows x 1 columns]

In [39]:
#df[df['Gender']== 'Woman']
df.loc[df['Gender']=='Woman',['Gender','Age','Ethnicity','LanguageWorkedWith']]

,Gender,Age,Ethnicity,LanguageWorkedWith
11,Woman,21.0,Black or of African descent,Bash/Shell/PowerShell;HTML/CSS;Java;Python;R;SQL
30,Woman,NaN,East Asian,Python
34,Woman,35.0,Black or of African descent,HTML/CSS;JavaScript
50,Woman,18.0,South Asian,Bash/Shell/PowerShell;C++;HTML/CSS;Java;JavaSc...
70,Woman,21.0,East Asian;South Asian,HTML/CSS;JavaScript;PHP;Python;SQL;VBA
...,...,...,...,...
88838,Woman,40.0,White or of European descent,Assembly;Java;JavaScript;Objective-C;Python
88844,Woman,27.0,White or of European descent,HTML/CSS;JavaScript;Python;SQL
88846,Woman,NaN,NaN,NaN
88854,Woman,23.0,White or of European descent,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
88855,Woman,NaN,NaN,Dart

In [52]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(1,27)
mydict = dict(zip(mylist, myarr))
#df2 = pd.Series(mydict)
#df2.head(10)
ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)
print(ser3.head())

a    1
b    2
c    3
e    4
d    5
dtype: int64

In [60]:
import numpy as np
L1 = np.arange(1,11)
L2 = np.arange(11,21)
print(L1,L2,sep='\t\t')
df3 = pd.DataFrame({'col1':L1,'col2':L2})
df3

[ 1  2  3  4  5  6  7  8  9 10]		[11 12 13 14 15 16 17 18 19 20]

   col1  col2
0     1    11
1     2    12
2     3    13
3     4    14
4     5    15
5     6    16
6     7    17
7     8    18
8     9    19
9    10    20

In [63]:
df3.loc[5,'col1']

6

In [104]:
a = np.arange(1,51)
a = a.reshape(5,10)
b = np.arange(51,101).reshape(5,10)
#myFrame = pd.concat([a,b],axis =1)
#myFrame
print(a)
print(b)
c = np.vstack((a,b))
c
d = np.swapaxes(c,0,1)
d

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
[[ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [105]:
myFrame = pd.DataFrame(d)
myFrame

    0   1   2   3   4   5   6   7   8    9
0   1  11  21  31  41  51  61  71  81   91
1   2  12  22  32  42  52  62  72  82   92
2   3  13  23  33  43  53  63  73  83   93
3   4  14  24  34  44  54  64  74  84   94
4   5  15  25  35  45  55  65  75  85   95
5   6  16  26  36  46  56  66  76  86   96
6   7  17  27  37  47  57  67  77  87   97
7   8  18  28  38  48  58  68  78  88   98
8   9  19  29  39  49  59  69  79  89   99
9  10  20  30  40  50  60  70  80  90  100

In [88]:
myFrame.loc[9,4]

50

In [109]:
print(myFrame.loc[:,0:1])

    0   1
0   1  11
1   2  12
2   3  13
3   4  14
4   5  15
5   6  16
6   7  17
7   8  18
8   9  19
9  10  20

In [113]:
myFrame.loc[:,0] + myFrame.loc[:,1]

0    12
1    14
2    16
3    18
4    20
5    22
6    24
7    26
8    28
9    30
dtype: int32

In [114]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [117]:
df['Country'] == 'United Kingdom'

0         True
1        False
2        False
3        False
4        False
         ...
88878    False
88879    False
88880    False
88881    False
88882    False
Name: Country, Length: 88883, dtype: bool

In [124]:
df.loc[(df['Country'] == 'United Kingdom') & (df['Gender'] == 'Woman')]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
475,477,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",United Kingdom,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,31.0,Woman,No,NaN,White or of European descent,Yes,Appropriate in length,Neither easy nor difficult
520,522,"I used to be a developer by profession, but no...",Yes,Less than once per year,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,41.0,Woman,No,NaN,White or of European descent,No,Appropriate in length,Easy
622,625,I am a developer by profession,No,Never,NaN,Employed full-time,United Kingdom,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A natural science (ex. biology, chemistry, phy...",...,Just as welcome now as I felt last year,NaN,32.0,Woman,No,Straight / Heterosexual,South Asian,No,Appropriate in length,Easy
649,652,"I am not primarily a developer, but I write co...",No,Less than once per year,"OSS is, on average, of LOWER quality than prop...",Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Information systems, information technology, o...",...,Somewhat more welcome now than last year,Tech meetups or events in your area;Courses on...,44.0,Woman,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
875,878,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",Fine arts or performing arts (ex. graphic desi...,...,Just as welcome now as I felt last year,NaN,32.0,Woman,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87796,88344,I am a student who is learning to code,Yes,Less than once per year,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",United Kingdom,"Yes, full-time",Some college/university study without earning ...,NaN,...,Not applicable - I did not use Stack Overflow ...,Tech articles written by other developers;Indu...,20.0,Woman,No,Bisexual,White or of European descent,No,Appropriate in length,Easy
88530,32941,NaN,No,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area,20.0,Woman,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
88686,56384,NaN,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","A humanities discipline (ex. literature, histo...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,29.0,Woman,No,Straight / Heterosexual,White or of European descent,No,Too long,Neither easy nor difficult
88704,59435,NaN,No,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","A natural science (ex. biology, chemistry, phy...",...,Somewhat less welcome now than last year,Courses on technologies you're interested in,28.0,Woman,No,Straight / Heterosexual,Multiracial,No,Appropriate in length,Easy
88854,84539,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Courses on technologies you're interested in,23.0,Woman,Yes,Bisexual,White or of European descent,No,Appropriate in length,Easy

In [137]:
df.loc[(df['Country'] == 'Pakistan') & (df['Gender']=='Woman'),['Country','Gender','BetterLife']]

        Country Gender BetterLife
868    Pakistan  Woman         No
1185   Pakistan  Woman         No
1489   Pakistan  Woman         No
3161   Pakistan  Woman         No
4682   Pakistan  Woman        Yes
5664   Pakistan  Woman         No
6457   Pakistan  Woman         No
6887   Pakistan  Woman         No
9340   Pakistan  Woman        Yes
17383  Pakistan  Woman        Yes
21326  Pakistan  Woman         No
24244  Pakistan  Woman        Yes
24634  Pakistan  Woman        Yes
24945  Pakistan  Woman        Yes
26697  Pakistan  Woman         No
26744  Pakistan  Woman        Yes
28583  Pakistan  Woman        Yes
32770  Pakistan  Woman        Yes
34995  Pakistan  Woman        Yes
35159  Pakistan  Woman        Yes
35745  Pakistan  Woman        Yes
36837  Pakistan  Woman        Yes
37435  Pakistan  Woman         No
42976  Pakistan  Woman        Yes
45504  Pakistan  Woman        Yes
48268  Pakistan  Woman        Yes
48923  Pakistan  Woman        Yes
49167  Pakistan  Woman        Yes
55846  Pakistan  Woman         No
59937  Pakistan  Woman         No
60213  Pakistan  Woman        Yes
61308  Pakistan  Woman        Yes
64421  Pakistan  Woman        Yes
68006  Pakistan  Woman        Yes
68917  Pakistan  Woman        Yes
70276  Pakistan  Woman         No
70557  Pakistan  Woman        Yes
70633  Pakistan  Woman         No
72682  Pakistan  Woman        Yes
81782  Pakistan  Woman         No
83148  Pakistan  Woman        Yes
83498  Pakistan  Woman        Yes
85582  Pakistan  Woman         No
88353  Pakistan  Woman        Yes

In [141]:
df1.loc['BetterLife','QuestionText']

'Do you think people born today will have a better life than their parents?'

In [161]:
future = df.loc[(df['Gender'] == 'Woman') & (df['Country'] == 'Pakistan'),'BetterLife']

AttributeError: 'Series' object has no attribute 'count_values'